name: 04 Shell's distintas
on:
  push:
    branches: ['main']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: bash
        shell: bash
        run: echo $0
      - name: sh
        shell: sh
        run: echo $0
      - name: por defecto
        run: echo $0  
