name: verificación de json 
on:
  push: 
    branches: ['main']
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5
        with:
          sparse-checkout: .

      - name: check node version
        run: node --version

      - name: instalación de jsonlint 
        run: |
          sudo apt-get update
          sudo apt-get install jsonlint

      - name: validar json
        run : sudo jsonlint-php package.json
