name: 06a Vars and secrets
on:
  workflow_dispatch:

env: 
  COLOR_PILDORA: ${{ vars.COLOR_PILDORA || 'Azul' }}

jobs:
  the-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Neo Election
        run: echo "Neo's Choice is ${{ env.COLOR_PILDORA }}"

      - name: know the truth
        if: ${{env.COLOR_PILDORA == 'Roja' }}
        run: |
          echo "The reality is not what you think Neo."
          echo " I will tell you a secret: ${{ secrets.TODO_ES_MENTIRA }}"
          echo "${{ secrets.TODO_ES_MENTIRA }}" | sed 's/./&/g' 
      - name: Get on with your life
        if: ${{ env.COLOR_PILDORA == 'Azul' }}
        run: echo "Get on with your life Neo"

  