name: runner context
on:
  workflow_dispatch:
jobs:
    runner_context:
        runs-on: ubuntu-latest
        steps:
          - name: Runner Context
            run: | 
              echo "Runner name: ${{ runner.name }}"
              echo "Runner context: ${{ runner.os }}"
              echo "Runner arch: ${{ runner.arch }}"
              echo "Runner environment: ${{ runner.environment }}"
          - name: build with logs
            run: |
              mkdir ${{ runner.temp }}/build_logs
              echo "Logs from building" > ${{ runner.temp }}/build_logs/build.logs
              exit 1
          - name: Upload logs on fail
            if: ${{ failure() }}
            uses: actions/upload-artifact@v4
            with:
              name: Build failure logs
              path: ${{ runner.temp }}/build_logs