name: runner context
on:
  workflow_dispatch:
jobs:
    runner_context:
        runs-on: ubuntu-latest
        steps:
          - name: Runner Context
            run: | 
              echo "Runner name: ${{ runner.name }}"
              echo "Runner context: ${{ runner.os }}"
              echo "Runner arch: ${{ runner.arch }}"
              echo "Runner environment: ${{ runner.environment }}"