name: 08a Control de flujos matriz
on:
    workflow_dispatch:
jobs:
    build:
        strategy:
            fail-fast: false #En la ejecución de la matriz si alguno falla continua 
            matrix:
                os: [ubuntu-22.01, ubuntu-20.04]
                version: [18,20]
                exclude:               #
                    - os: ubuntu-22.04 # De la matriz se indica que no haga nada en la versión indicada
                      version: 20      # 
        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v6
            - name: setup node environment
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.version}}
            - if: matrix.os == 'ubuntu-22.04' && matrix.version == 20
              run: exit 1
              continue-on-error: true # En caso de que la tarea falle continua el preoceso como bueno

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy
              run: echo "Desplegando... bib bib bob pup bib bip..."