name: a9 - caché
on:
  workflow_dispatch:
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Carga de los datos  
        uses: actions/checkout@v4
      - name: asignar versión de node
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - name: Uso de cache
        uses: actions/cache@v4
        id: cache
        with:
          #path: ~/.npm
          path: node_modules
          key: ${{ runner.os}}-npm-${{hashFiles('**packege-lock.json')}}
      - name: Instalar dependencias
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lanzar pruebas
        run: npm test


