name: 10a - entornos
on:
  push:
    branches:
     - main
     - release/*
  workflow_dispatch:
jobs:
  entornos:
    runs-on: ubuntu-latest
    environment: prod
    steps:
        - name: verificar variables
          run: echo "${{vars.UNA_VARIABLE}}"
        - name: Verifica secreto
          run: echo "${{ secrets.UN_SECRETO }}"