name: 10a-2 entornos 
on:
    push:
        branches: ['main']
    workflow_dispatch:

jobs:
    entornos:
        runs-on: ubuntu-latest
        environment: testing
        steps:
            - name: Verificar variable
              run: echo "${{vars.UNA_VARIABLE}}"
            - name: Verificar secreto
              run: echo "${{vars.UN_SECRETO}}" 
