name: 10a-2 entornos 
on:
    push:
        branches: ['main']
    workflow_distpatch:
        
jobs:
    entornos:
        runs-on: ubuntu-latest
        evironment: testing
        steps:
            - name: Verificar variable
              run: echo "${{vars.UNA_VARIABLE}}"
            - name: Verificar secreto
              run: echo "${{vars.UN_SECRETO}}"