name: 11b[Llamado] - Ejercicio de workflow reutilizable.
on:
    workflow_call:
        inputs:
            versiones_node:
                required: true
                type: string
                default: "['18','20']"
                description: 'Las versiones de node sobre las que se va a probar'
jobs:
    build:
        strategy:
            matrix:
                version: ${{fromJson(inputs.versiones_node)}}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: setup node environment
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.version}}
            - run: npm ci
            - run: npm test